# You've seen properties as things link hibernate.connection.url
# server.port=
# server.servlet.context-path=
server:
  port: 9004
  servlet:
    context-path: /
# in a properties file, it would look like spring.application.name
spring:
  application:
    name: overflowingstacks
    datasource:
    driver-class-name: org.postgresql.Driver
      url: {DBURL}
      username: {DBUSER}
      password: {DBPASS}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        includes:
          - "beans"
          - "health"
          - "info"
